#
# ~/.bashrc
#

# Pruned EndeavourOS defaults
alias ls="ls --color=auto"
alias ll="ls -la --color=auto"
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

# Stuff I copied from the internet

# Dotfiles Git setup
# https://wiki.archlinux.org/title/Dotfiles#Tracking_dotfiles_directly_with_Git
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
source /usr/share/bash-completion/completions/git
__git_complete config __git_main

# Eternal bash history.
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# https://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# https://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
# My addition also preserves the exit code from the last process run, since `history -a` always succeeds.
PROMPT_COMMAND="STATUS=$?; history -a; (exit $STATUS)"

# Autogenerated configs

# nvm configuration
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# pnpm
export PNPM_HOME="/home/ecxyzzy/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# My own stuff

# PATH
export PATH="$PATH:/home/ecxyzzy/.local/share/JetBrains/Toolbox/scripts:/home/ecxyzzy/.local/bin:/home/ecxyzzy/bin"

# Fallback prompt that still looks cool if running in a terminal without omp support (e.g. ttyN)
export PS1='\[\e[0;32m\]\u\[\e[m\]@\[\e[0;32m\]\h\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[1;32m\]\$\[\e[m\] '

# The One True Editor
export EDITOR=vim

# Initialize OMP with my preferred config
eval "$(oh-my-posh init bash --config /usr/share/oh-my-posh/themes/slimfat.omp.json)"

# kitty ssh
[[ "$TERM" = "xterm-kitty" ]] && alias ssh="kitty +kitten ssh"

# because no archbtw bashrc would be complete without invoking neofetch when starting every session
neofetch
