#!/usr/bin/env bash

if [ "$(playerctl -p spotify status 2>&1)" != "No players found" ]; then 
    title=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|grep -EA 1 "title"|cut -b 44-|cut -d '"' -f 1|grep -Ev ^$)
    artist=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|grep -EA 2 "artist"|cut -b 20-|cut -d '"' -f 2|grep -Ev ^$|grep -Ev array|grep -Ev artist)
    echo " ${artist} :: ${title}"|sed 's/&/&amp;/g'
fi
